### PR TITLE
tutorial 4

### PR DESCRIPTION
**Pull request by shirubana**
Working on the content on tutorial 4. Did not move anything around but:
- broke big text cells into more cells
- added more images
-added section of PV concepts and Python concepts
- Added Colored Note Boxes to go visit datasheet of the modules being used, and the PVFree website

### CODE REVIEW

**Comment by mikofski** [comment]
Hi @shirubana I rebased your branch against main, and updated it. You need nbdime in order to merge notebooks. It works fine, no conflicts! Thanks Git! (& nbdime):

    pvsc48-python-tutorial (main) $ git co tut_4_more_images
    pvsc48-python-tutorial (tut_4_more_images) $ conda activate myenv
    (myenv) pvsc48-python-tutorial (tut_4_more_images) $ conda install nbdime
    (myenv) pvsc48-python-tutorial (tut_4_more_images) $ git rebase main 
    [I nbmergeapp:70] Merge result written to .merge_file_b21888
    Successfully rebased and updated refs/heads/tut_4_more_images.

### before rebase:
image

### after rebase
image

### view diff using nbdime:

    (myenv) pvsc48-python-tutorial (tut_4_more_images) $ nbdime diff-web tut_4_more_images main
    [I nbdimeserver:409] Listening on 127.0.0.1, port 50165
    [I webutil:29] URL: http://127.0.0.1:50165/difftool

[nbdime-diff-web_tut_4_more_images.zip](https://github.com/mikofski/PVSC48-Python-Tutorial/files/6388086/nbdime-diff-web_tut_4_more_images.zip)

**Comment by mikofski** [comment]
Thanks so much @shirubana this is a vast improvement. Do you want me to take over from here or do you want to make more changes? Everything is now sync'd up here on GitHub, so can just pull the `tut_4_more_images` branch to your local machine to refresh your working copy, and then you should be all good.

**Comment by mikofski** [comment]
How do you all feel about mixing HTML, CSS, and Markdown? There are two cells which suddenly have HTML and call a CSS class which I don't believe is guaranteed to be in all environments:

```html
<div class="alert alert-block alert-info">
<b>Let's Explore:</b>
<a href='https://www.ecodirect.com/Canadian-Solar-CS6X-300M-300W-36V-PV-Panel-p/canadian-solar-cs6x-300m.htm'>
Click here to see the panel's Datasheet.
</a></div>
```

This produces a nice blue box, but IMHO, I don't think it's necessary.
image

IMO the goal of this tutorial is to teach users how to use Jupyter, python, pvlib, etc. to write easy code snippets to explore and analyze PV performance. I don't think exposing them to HTML is a good idea, at least not something fancy. I think we should Keep It Super Simple (KISS) and just use the purest markdown and python we can, and not get too fancy. What will keep them engaged are opportunities to try to run the code snippets, and to try to write and run their own snippets. We have this JupyterHub technology as a teaching platform -- that's were I'd put my energy and leverage JupyterHub to make this tutorial successful.

**Comment by shirubana** [comment]
Hey, it'd be great if you update some more the tutorial 4. I'll work tomorrow morning a bit on adding some more interaction to one of the previous ones.

with the blue box, I was trying to do a different way of showing content, not really expecting them to see the code behind. I used it on two parts to mark webpages that I think we should click during hte lesson and show the content so they can relate the code to what they will encounter when browsing for panels, datasheets, the PVFree website, etc. 

the blue box was on one of the markdown tutorials webpages. I don't think we are expecting them to double click and understand markdown I agree or html, but I also dont think that means we should abstain for making the tutorial pretty and readable -- textbooks have call outs to more information, different sections, further readings. that's what I'm trying to achieve

**Comment by mikofski** [comment]
>with the blue box, I was trying to do a different way of showing content, not really expecting them to see the code behind. I used it on two parts to mark webpages that I think we should click during hte lesson and show the content so they can relate the code to what they will encounter when browsing for panels, datasheets, the PVFree website, etc.
>
>the blue box was on one of the markdown tutorials webpages. I don't think we are expecting them to double click and understand markdown I agree or html, but I also dont think that means we should abstain for making the tutorial pretty and readable -- textbooks have call outs to more information, different sections, further readings. that's what I'm trying to achieve

OK, good point. Let's leave it. Thanks!

>Hey, it'd be great if you update some more the tutorial 4. I'll work tomorrow morning a bit on adding some more interaction to one of the previous ones.

Sounds good. I'll take a crack at making the changes you suggested. Thanks!

**Comment by mikofski** [comment]
Hi @shirubana , any chance you could open a new PR from main? Since the title of this PR is tutorial 4 seems to make sense that it would only have changes to tutorial 4? This will make merging and reviewing much easier if features are isolated to individual feature branches. Shouldn't be any issues if two PR's are both branched from main but work in different files. okay? thx!

**Comment by mikofski** [comment]
Maybe I should just merge this into main, and we can both start fresh?

**Comment by shirubana** [comment]
0:) yes please

**Comment by mikofski** [comment]
These new figures are great! This tutorial is awesome! Thanks so much for all your hard work!!!

**Pull request merged**
